config/routes.rb
require 'sidekiq/web'

FantasyRocket::Application.routes.draw do
  resource :users
  resources :sessions
  resources :password_resets

  resources :leagues do
    resources :league_memberships, as: 'memberships'
    resource :drafts
  end

  resources :draft_picks

  resources :regular_season_games

  resources :games_creators, only: [:create]

  mount Sidekiq::Web, at: '/sidekiq'

  root 'splash#index'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def create
    if user = User.find_by_email(params[:email].andand.downcase)
      user.generate_token(:password_reset_token)
      user.password_reset_sent_at = Time.now
      user.save!

      PasswordResetMailerWorker.perform_async(user.id)
    end

    redirect_to root_url, notice: "Email sent with password reset instructions"
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_url, :alert => "Password reset has expired."
    elsif @user.update_attributes(user_params)
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.haml
.centered-form
  %h1.form-title Enter new password

  = form_for @user, url: password_reset_url(params[:id]) do |f|
    .form-group
      = f.password_field :password, class: "form-control input-lg", placeholder: "New password"
    .form-group
      = f.password_field :password_confirmation, class: "form-control input-lg", placeholder: "Password confirmation"
    .actions
      = submit_tag "Update password", class: "btn btn-main btn-xlg"

app/views/password_resets/new.html.haml
.centered-form
  %h1.form-title Enter email address

  = form_tag password_resets_url, method: :post do
    = hidden_field_tag :redirect_to, params[:redirect_to]
    .form-group
      = text_field_tag :email, params[:email], class: "form-control input-lg", placeholder: "Email address"
    .actions
      = submit_tag "Reset password", class: "btn btn-main btn-xlg"