config/routes.rb
require 'sidekiq/web'

FantasyRocket::Application.routes.draw do
  resource :users
  resources :sessions
  resources :password_resets

  resources :leagues do
    resources :league_memberships, as: 'memberships'
    resource :drafts
  end

  resources :draft_picks

  resources :regular_season_games

  resources :games_creators, only: [:create]

  mount Sidekiq::Web, at: '/sidekiq'

  root 'splash#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, email: true

  # validates :auth_token, presence: true, uniqueness: true

  has_many :commissioned_leagues, class_name: "League", foreign_key: "commissioner_id", inverse_of: :commissioner

  has_many :league_memberships, foreign_key: "member_id"
  has_many :leagues, through: :league_memberships
  has_many :draft_picks, foreign_key: "member_id", inverse_of: :member

  has_one :subscription, -> { where(:canceled_at => nil) }
  has_one :canceled_subscription, -> { where('canceled_at IS NOT NULL').order('canceled_at DESC') }, class_name: "Subscription"

  before_validation -> { self.email = email.downcase.strip  if email_changed? }

  before_create { generate_token(:auth_token) }

  def subscriber?
    !!subscription or (canceled_subscription && !canceled_subscription.expired?)
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  # helps combine user accounts (common if someone mistypes email address)
  # TODO remove when we add proper email validation and confirmation
  def assimilate_user!(user)
    League.where(commissioner_id: user.id).each do |l|
      l.update_attributes!(commissioner_id: id)
    end
    LeagueMembership.where(member_id: user.id).each do |lm|
      begin
        lm.update_attributes!(member_id: id)
      rescue ActiveRecord::RecordInvalid
        lm.destroy!
      end
    end
    DraftPick.where(member_id: user.id).each do |lm|
      lm.update_attributes!(member_id: id)
    end
    user.destroy!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :current_user!, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user(@user)

      # join user to a league if specificed
      if params[:league_id].presence
        league = League.find(params[:league_id])
        league.add_member(@user)  if league.hmac == params[:h]
      end

      redirect_to params[:redirect_to].presence || new_league_url, notice: "Thank you for signing up!"
    else
      render template: "users/new"
    end
  end

  def edit
  end

  def update
    if current_user.update_attributes(user_params)
      redirect_to root_url, notice: "Thanks! We got your changes."
    else
      flash.now.alert = "That didn't work."
      render "edit"
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/edit.haml
- content_for(:title) { "Settings" }

.centered-form
  %h1.form-title Settings

  = form_for current_user, url: users_url do |f|
    - if current_user.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
        - current_user.errors.full_messages.each do |message|
          %li= message

    .form-group
      = f.text_field :name, class: "form-control input-lg", placeholder: "First and Last name"
    .form-group
      = f.text_field :email, class: "form-control input-lg", placeholder: "Email address"
    .form-group
      = f.password_field :password, class: "form-control input-lg", placeholder: "Password"
    .form-group
      = f.password_field :password_confirmation, class: "form-control input-lg", placeholder: "Confirm password"

    .actions
      = f.submit "Save", class: "btn btn-main btn-xlg", data: {disable_with: "Saving..."}

app/views/users/new.haml
.centered-form
  %h1.form-title Sign Up
  %p
    Already use Fantasy Rocket?
    = link_to "Login", new_session_path(redirect_to: params[:redirect_to], league_id: params[:league_id], h: params[:h])

  = form_for @user do |f|
    = hidden_field_tag :redirect_to, params[:redirect_to]
    = hidden_field_tag :league_id, params[:league_id]
    = hidden_field_tag :h, params[:h]

    - if @user.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
        - @user.errors.full_messages.each do |message|
          %li= message

    .form-group
      = f.text_field :name, class: "form-control input-lg", placeholder: "First and Last name"
    .form-group
      = f.text_field :email, class: "form-control input-lg", placeholder: "Email address", type: 'email'
    .form-group
      = f.password_field :password, class: "form-control input-lg", placeholder: "Password"
    .form-group
      = f.password_field :password_confirmation, class: "form-control input-lg", placeholder: "Confirm password"

    .actions
      = f.submit "Sign Up", class: "btn btn-main btn-xlg"

:coffee
  mixpanel.track("SignUpForm Show")
  mixpanel.track_forms(".centered-form form", "SignUpForm Submit")