config/routes.rb
require 'sidekiq/web'

FantasyRocket::Application.routes.draw do
  resource :users
  resources :sessions
  resources :password_resets

  resources :leagues do
    resources :league_memberships, as: 'memberships'
    resource :drafts
  end

  resources :draft_picks

  resources :regular_season_games

  resources :games_creators, only: [:create]

  mount Sidekiq::Web, at: '/sidekiq'

  root 'splash#index'

end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    if current_user && league = current_user.leagues.where(sport: current_sport).first
      return redirect_to league
    end
  end

  def pricing
  end
end

app/views/splash/index.haml
.splash
  .intro{class: current_sport}
    %h1= sport_t("splash.title").html_safe
    %h2= sport_t "splash.subtitle"
    .create-league= link_to "Start a league<span class='hidden-for-mobile'>. #{sport_t "splash.sub_cta"}</span>".html_safe, new_users_url, class: "btn btn-main btn-xlg"
  .quote
    .container
      .clearfix
        .quote-text "I love this pool. My friends love this pool. And now, you can love this pool."
        .quote-author - Bill Simmons, ESPN, Grantland
      = link_to "Read more", "http://www.grantland.com/blog/the-triangle/post/_/id/36155/you-should-have-an-nfl-wins-pool", class: "read-more"
  .how-it-works{class: current_sport}
    .container
      .row
        .col-md-12
          %h3 How It Works
      .row
        .col-md-4
          %h4 1. Create a league
          %p Create a league, invite your friends (we allow between 2 and 15 players), and agree on an entry fee and prize money.
        .col-md-4
          %h4 2. Draft your teams
          %p We randomly assign each league member a number that determines draft order. Each member picks the teams they think will win the most games until there are no teams left. We use our special algorithm to determine when each member drafts in order to even the probability fairly.
        .col-md-4
          %h4 3. Win
          %p The member whose teams win the most regular season games wins the pool. And that's it! No agonizing over benching players every game day. Just sit back and watch who wins.
    .create-league= link_to "Start a league<span class='hidden-for-mobile'>. #{sport_t "splash.sub_cta"}</span>".html_safe, new_users_path, class: "btn btn-main btn-xlg"

:coffee
  mixpanel.track("Splash Show")
  mixpanel.track_links(".splash .create-league a", "Splash CreateLeague Click")

app/views/splash/pricing.haml
.container.container-under-header.pricing
  %table.table.black-table.pricing-table
    %thead
      %tr
        %th Free
        %th.focus Premium
      %tbody
        %tr
          %td
            %ul.checkmarks
              %li Draft
              %li Standings
              %li Weekly emails
          %td
            %ul.checkmarks
              %li Draft
              %li Standings
              %li Weekly emails
              %li Expected wins
              %li Team schedules
              %li Average draft positions
              %li Trade analysis
              %li Create multiple pools
            - unless current_user.andand.subscriber?
              = link_to "Sign up", new_user_subscriptions_url(current_user), class: "btn btn-xlg btn-main"
  .price