config/routes.rb
require 'sidekiq/web'

FantasyRocket::Application.routes.draw do
  resource :users
  resources :sessions
  resources :password_resets

  resources :leagues do
    resources :league_memberships, as: 'memberships'
    resource :drafts
  end

  resources :draft_picks

  resources :regular_season_games

  resources :games_creators, only: [:create]

  mount Sidekiq::Web, at: '/sidekiq'

  root 'splash#index'

end

app/views/layouts/application.haml
<!DOCTYPE html>
%html
  %head
    %title= yield(:title).presence || "#{t(:site_name)} - Home of the NFL Wins Pool"
    %link{href: '//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700', rel: 'stylesheet'}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %meta{name: "description", content: t(:description)}
    %meta{property: "og:description", content: t(:description)}
    %meta{property: "og:site_name", content: t(:site_name)}
    %meta{property: "og:image", content: asset_url('og_image.jpg')}
    :javascript
      (function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
      mixpanel.init("#{ENV['MIXPANEL_API_KEY'] || 'e68b22111bfe9c0cd6b8fc54d6f4a480'}");
  %body
    .flash-messages
      - flash.each do |name, message|
        - if message.is_a?(String)
          .flash-message{:class => "alert alert-#{name == :notice ? "success" : "warning"}"}
            %div{:id => "flash_#{name}"}= message
    .logo-wrap= link_to image_tag('logo.png', alt: t(:site_name), class: "logo"), root_url
    .navbar.navbar-default
      .container
        .navbar-header
          %button.navbar-toggle{type: "button", 'data-toggle' => "collapse", 'data-target' => ".navbar-right-links-collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        .links.clearfix.collapse.navbar-collapse.navbar-right-links-collapse
          %ul.nav.navbar-nav
            %li= link_to "Blog", "http://blog.fantasyrocket.com", class: "header-link blog", target: "_blank"
            %li= link_to "FAQ", "http://faq.fantasyrocket.com", class: "header-link how-it-works", target: "_blank"
            - if current_user
              %li
                .dropdown.navbar-right
                  %a.header-link{href: "#", 'data-toggle' => "dropdown"}
                    = current_user.name
                    %b.caret
                  %ul.dropdown-menu
                    - if current_user.leagues.size > 0
                      - current_user.leagues.each do |league|
                        %li= link_to league.name, league
                      %li.divider
                    %li= link_to "+ Start a League", new_league_url, class: "dropdown-create-league"
                    %li.divider
                    %li= link_to "Settings", edit_users_url
                    %li= link_to "Log Out", session_url("current"), method: "delete"
            - else
              %li= link_to "Start a league", new_users_url, class: "header-link create-league"
              %li= link_to "Sign in", new_session_url, class: "header-link"
    = yield

    :javascript
      (function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/fpLzLWpHGQhNF3MD3nULOQ.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()

      UserVoice = window.UserVoice || [];
      UserVoice.push(['showTab', 'classic_widget', {
        mode: 'full',
        primary_color: '#cc6d00',
        link_color: '#007dbf',
        default_mode: 'support',
        forum_id: 221272,
        tab_label: 'Feedback',
        tab_color: '#cb6330',
        tab_position: 'middle-left',
        tab_inverted: true
      }]);

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-43758213-1', 'fantasyrocket.com');
      ga('send', 'pageview');

    :coffee
      mixpanel.track_links(".header .create-league", "Header CreateLeague Click")
      mixpanel.track_links(".header .how-it-works", "Header HowItWorks Click")
      mixpanel.track_links(".header .dropdown-create-league", "Header Dropdown CreateLeague Click")
      $ ->
        new FlashView()